name: Sincronización con Máquina en clouding.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm i --force

      - name: Instalar sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Verificar instalación de sshpass
        run: |
          if ! command -v sshpass > /dev/null 2>&1; then
            echo "Error: sshpass no está instalado correctamente"
            exit 1
          fi

      - name: Ejecutar scp y comando remoto
        run: |
          sshpass -p fPes3VjKf72tygrs scp -r root@161.22.44.43:/pruebas C:\Users\angel.suelves\prueba.txt
          
      - name: Verificar resultado del comando remoto
        run: |
          if [ $? -eq 0 ]; then
            echo "La contraseña proporcionada es correcta"
          else
            echo "La contraseña proporcionada es incorrecta"
            exit 1
          fi

