name: Sincronización con Máquina en clouding.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm i --force

      # Ejecutar instalación de sshpass
      - name: Instalar sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
      # Verificar que sshpass esté instalado correctamente
      - name: Verificar instalación de sshpass
        run: |
          if ! command -v sshpass > /dev/null 2>&1; then
            echo "Error: sshpass no está instalado correctamente"
            exit 1
          fi

      # Ejecutar el comando scp y el comando remoto
      - name: Ejecutar scp y comando remoto
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* root@161.22.44.43:/pruebas/
          RESULT=$(sshpass -p ${{ secrets.MI_CONTRASENA_SECRETA }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@161.22.44.43 "chmod -R 755 /pruebas; echo \$?")  

      # Verificar el resultado del comando remoto
      - name: Verificar resultado del comando remoto
        run: |
          if [[ $RESULT -eq 0 ]]; then
            echo "La contraseña proporcionada es correcta"
          else
            echo "La contraseña proporcionada es incorrecta"
            exit 1
          fi
