name: Sincronización con Máquina en clouding.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm i --force

      - name: Copiar repositorio completo a la máquina en clouding.io
        env:
          IP: 161.22.44.43
          USER: root
          PASSWORD: ${{ secrets.MI_CONTRASENA_SECRETA }}
        run: |
          sudo apt-get install -y sshpass
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* ${{ env.USER }}@${{ env.IP }}:/pruebas/
          # Ejecutar comando remoto y almacenar el resultado en una variable
          RESULT=$(sshpass -p ${{ env.PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.USER }}@${{ env.IP }} "chmod -R 755 /pruebas; echo \$?")  
          # Verificar si el resultado es igual a 0, lo que significa que el comando se ejecutó correctamente
          if [[ $RESULT -eq 0 ]]; then
            echo "La contraseña proporcionada es correcta"
          else
            echo "La contraseña proporcionada es incorrecta"
          fi
